### PR TITLE
#50 - DataSet Validator factory decoupling

### LINKED ISSUE #12: Investigate different input validation rule support
Currently the base library (and all dependents) relies on Laravel validation rule.

While that is not an issue itself, the use of Laravel Facades, blocks adding pure Unit Tests on some Providers, as an error `RuntimeException: A facade root has not been set.` is thrown from the `\Upmind\ProvisionBase\Provider\DataSet\RuleParser::getValidator()`.

Investigate & discuss options
- Avoid use of Facades, maybe load the Validation Factory (which the Facade triggers) via the constructor of the relevant methods
- Use of a different library like [Respect\Validation](https://github.com/Respect/Validation)

### LINKED ISSUE #50: Decouple DataSet from Validator Factory
As a stop-gap, instantiation happens inside the DataSet class using the `Validator::` facade. 

One suggestion for improvement would be to have a static setter/getter for a validator factory so this can be defined in a service provider and swapped out in tests

### PR DESCRIPTION
**Pull request by RoussKS**
Closes #50 
Closes #12 

- Allows custom validator setter to prevent using the factory, this helps with easier Unit Tests
- Removes all Facades Dependencies from the Larave Service Provider
- Set validator factory via service provider once & forget
- Added Init Unit Testing to confirm functionality without Facade
- Added github actions workflow for tests
- Updated static analysis github actions workflow to cover `v5-dev` branch

### CODE REVIEW

File: src/Laravel/ProvisionServiceProvider.php [hunk 1]
```diff
@@ -95,8 +95,10 @@ protected function bootRegistry(): void
         // Attempt to set the Registry instance from cache
         if ($cachedRegistry = $cache->get(self::REGISTRY_CACHE_KEY)) {
             try {
-                $registry = unserialize($cachedRegistry);
-            } catch (Throwable $e) {
+                $registry = unserialize($cachedRegistry, ['allowed_classes' => [Registry::class]]);
```
Comment (adamquaile) [inline src/Laravel/ProvisionServiceProvider.php]: Am I right in thinking this is a more complex object graph of categories, each with their own classes and types? I'd have thought we'd need to add more types to this allowlist?

**Review by adamquaile — COMMENTED** [review]
I'll leave the majority of this to @uphlewis to review, since he knows the validator context way better than I do. 

One question about the `unserialize` call, but looks good 👍

File: src/Laravel/ProvisionServiceProvider.php (hunk 1 above)
Comment (RoussKS) [reply src/Laravel/ProvisionServiceProvider.php]: Hm, not really sure, I think it just needs the class that is serialized (regardless of what's included). Not entirely sure, might need to play around a bit more
PHPStorm flagged it like it should fixed, hence added.

Comment (adamquaile) [reply src/Laravel/ProvisionServiceProvider.php]: https://3v4l.org/kieEO

It seems to unserialize but it will create a `__PHP_Incomplete_Class`. If you add a type-hint on `B` in that linked example it'll error out.

Comment (RoussKS) [reply src/Laravel/ProvisionServiceProvider.php]: So, if we want to use that, we will need to add all the potential classes? hm, that's not really helpful.

I think I need to set it to `true` then to serialize all.
Thanks for flagging that!

Comment (uphlewis) [reply src/Laravel/ProvisionServiceProvider.php]: Yeh since its internally cached and unserialized im not concerned about a security risk of allowing all classes

**Review by uphlewis — APPROVED** [review]
Great stuff- really good and much needed improvements, thanks!

**Comment by uphlewis** [comment]
[Provision Base library - Decouple Laravel Facade Validator Factory](https://trello.com/c/Oyjg37un/11-provision-base-library-decouple-laravel-facade-validator-factory)
